### ISSUE TITLE
Peer-to-peer-code-review

### ISSUE THREAD

**Issue by Mofuhidy** [batoolfatima2135/Awesome-books#2]
Your code is great 👍🏾  everything works properly.
## What needed to be changed: 
I think the collection that saved the books' objects .. kindly consider it to be empty without hard-coded objects.

**Comment by yemidada** [comment]
In addition to earlier feedback, you didn't load local storage data when there is content

**Comment by batoolfatima2135** [comment]
Hey, Thanks a lot for your valuable input 👍 
I'm closing this issue because every issue that you mentioned is solved now!
keep supporting 💯
