### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by Chandan-devs-tech** [batoolfatima2135/Awesome-books#5]
Hi @batoolfatima2135 ,

- You have done a great job so far there are some required changes to be made in javascript as described below:
# Required Changes ♻️ 
- you should resolve the EsLint linters issue with the 'deleteBooks' function.
- you need to add validation in the form using Javascript.
- You should display all the books from Local storage when the page is reload.
<img width="846" alt="fa" src="https://github.com/batoolfatima2135/Awesome-books/assets/65088027/3ab6e707-f802-4fd7-bc77-d36fafde9837">
<img src="https://media2.giphy.com/media/cMJHOY2jGEHn2L48PC/giphy.gif"/>

**Comment by batoolfatima2135** [comment]
Hey!
Thanks a lot for this valuable input! 👍  there is always room for some improvements! 
I've applied all the changes that you mentioned.
Keep supporting 👍
